### ISSUE TITLE
Codebase Walkthrough

### ISSUE THREAD

**Issue by colshacol** [Marcisbee/radi#12]
I'll admit, I've been a functional Nazi for a little over 2 years now, so I don't even possess the skills necessary to understand this code. I've put it together a little bit in my head by debugging the `refactor` branch, but as a whole I still can not follow it.

I'd like to discuss setting up a screen-share for somebody to give a tour of Radi's code and how it works. I think it would greatly help me, and I also can not be the only one experiencing difficulty.

**Comment by ambewas** [comment]
you and me both buddy, we'll need some sort of a schematic to make sense of it all. As discussed, I suggest doing this after the current refactor has split up the code
