### ISSUE TITLE
User facing API breaking changes

### ISSUE THREAD

**Issue by Marcisbee** [Marcisbee/radi#36]
## Backstory

In the beginning of this project I wanted to build framework, that is super fast (to skip virtual dom and implement listeners as re-rendering engine) and to use it for my own development purposes. So in the beginning I wanted it to be functional...

Then the unexpected popularity and refactor came, when it kinda fell into OOP all the way. With that came somewhat unexpected bumps and listeners became kinda hard to work with. In my head I always tried to figure out what is the way I want v1 to be and I think I finally figured it out.

## Functional all the way

This means different user facing API and different way of thinking about writing components. Code got even smaller and faster this way too.

So the idea is that, components no longer have their own state, instead we now got `Store`. We can create as many stores as we want, even for every component, if so pleased. And only one way of rendering DOM with functional stateless components.

##### 1. just rendering dom
```jsx
const { h, mount } = Radi

function Hello() {
  return (
    <h1>Hello World !</h1>
  )
}

mount(<Hello/>, document.body)
```

##### 2. rendering dom with variable data
```jsx
const { h, mount, Store } = RadiExperiment

/* Firstly we define state */
const state = new Store({
  count: 0
})

/* Then we define some actions that will change state */
const up = ({count}, by) => ({count: count + by})
const down = ({count}, by) => ({count: count - by})

/* Then comes pure function component */
function Counter() {
  return (
    <div>
      <h1>{ state.out(s => s.count) }</h1>
      <button onclick={ () => state.dispatch(up, 1) }>Up</button>
      <button onclick={ () => state.dispatch(down, 1) }>Down</button>
    </div>
  )
}

/* Finally we mount it */
mount(<Counter/>, document.body)
```

None of the lifecycles suffer either.

```jsx
function App() {
  this.onMount = () => {}
  this.onDestroy = () => {}

  return <Person/>
}
// or we can set prototypes too
App.onMount = () => {}
App.onDestroy = () => {}
```

### More about `Store`

With new Store we can do some interesting things. Like getting data from API by just defining schema of response data. So we can introduce `Fetch` that gathers data from api and directly injects them in Store.

Also why not inject one Store into another one (sync them both or lock injected).

```jsx
// First we define Schema for our data from API
const User = new Fetch.get(
  '/users/:id',
  (data) => ({
    id: data._key,
    firstname: data.firstname,
    lastname: data.lastname,
  })
)

// Then we create store where we include our User Schema
const userStore = new Store({
  foo: 'bar',
  user: User({id: 10}),
})

// This part is not necessary, but for demo purpose it's here
// Here we inject `userStore` store into another store
const appStore = new Store({
  person: {
    fakeAge: 21,
    data: userStore.inject,
  }
})

// Finally we can use our data. API will gather data automatically
function App() {
  return (
    <h1>
      {appState.out(({person}) => (
        person.data.firstname + ' ' + person.data.lastname
      ))}
    </h1>
  )
}
```

This is what v1 will eventually look like. There is some work in progress already in [huskey branch](https://github.com/radi-js/radi/tree/huskey) if you want to check it out.

---

Here are some live examples:

- [Counter example](https://codepen.io/Marcisbee/pen/JaOpbj)
- [Sinwave example](https://codepen.io/Marcisbee/pen/QVmaML)

**Comment by rafaelklaessen** [comment]
I actually really like this. This is a significant improvement :smile:

**Comment by ambewas** [comment]
Looking good, honestly. 

Feels very react + store (redux/whatever) like, honestly. So I've got a couple of questions:
- with the `Listener`s gone, where's the difference with a component framework like react/preact/.. ? 
- how does the `app` component in your last example know it needs to re-render when `appState` changes? What are you using under the hood, and how does `App` know about it? (or will it never, and is it again just the value updating? In that case, how are you doing this without `Listener` ?

I lost interest a little bit in radi with all the OOP stuff going on all of a sudden, but if you're going functional all the way, I'd love to contribute again! Any work that needs to be done?

**Comment by Marcisbee** [comment]
@ambewas Good questions!

- Listeners are not gone. Concept is still there, but moved from components to `Store`.
- Components do not re-render them selves, instead listeners (same as before) from Store does.

There are still bunch of features that needs to be moved from current Radi to this and tests have yet to be written.

### Features still missing:
- Unit tests
- `customAttribute`
- `customTag`
- Need to figure out neat way to inject data from Events.
For example just like `Fetch` wich isn't yet finished either.

```jsx
const { subscribe, Store } = Radi

const mousePosition = subscribe(document.onmousemove, e => ({x: e.x, y: e.y}))

new Store({
  mousePosition
})
```
or if anyone have better solution.

- Custom attribute `model` on input fields for two way data binding with store
- And most of custom tags and attributes that were written for Radi

If some points feels interesting to you than PR's would be welcome :)

**Comment by rafaelklaessen** [comment]
Reminds me of Rx's `Observable` a lot...Might want to use that with the store?

**Comment by Marcisbee** [comment]
@rafaelklaessen I don't intend Radi to rely on any 3rd party dependency.
Observables can be used separately, if so desired.

**Comment by rafaelklaessen** [comment]
@Marcisbee Alright, I get that. But you could take inspiration from its API :smile:
