### ISSUE TITLE
Example showing list/table updates

### ISSUE THREAD

**Issue by bluenote10** [Marcisbee/radi#53]
After reading the docs I still have difficulties understanding how to use radi in practice. In particular, what about more complex updates that do not just affect a single element? For example rearraginging/modifying/removing/adding children to a node. It would help to see e.g. an example of mapping a 2d array of values to a `<table>`.

**Comment by Marcisbee** [comment]
Hey.

Template engine uses JSX syntax, so what JSX can do, so can Radi.

Here's an example or 2d table: https://radi.js.org/#/fiddle/code=c3RhdGU6IHsKICBhc3NldHM6IFsKICAgIFsnTmFtZScsICdTaXplJ10sCiAgICBbJ2Zvby5naWYnLCAnNDVrYiddLAogICAgWydiYXIucG5nJywgJzEya2InXSwKICAgIFsnYmF6LmpwZycsICc5a2InXSwKICBdCn0KCkBhY3Rpb24gcmVtb3ZlKGluZGV4KSB7CiAgY29uc3QgYXNzZXRzID0gdGhpcy5zdGF0ZS5hc3NldHMuc2xpY2UoKTsKICBhc3NldHMuc3BsaWNlKGluZGV4LCAxKTsKICByZXR1cm4gewogICAgYXNzZXRzCiAgfQp9CgpAYWN0aW9uIGFkZCgpIHsKICByZXR1cm4gewogICAgYXNzZXRzOiBbCiAgICAgIC4uLnRoaXMuc3RhdGUuYXNzZXRzLAogICAgICBbJ25ldy5naWYnLCBNYXRoLnJvdW5kKE1hdGgucmFuZG9tKCkgKiAzMCkgKyAna2InXQogICAgXQogIH0KfQoKPHRlbXBsYXRlPgogIDxzdHlsZT4KICAgIHtgdGFibGUsIHRyLCB0ZCB7IGJvcmRlcjogMXB4IHNvbGlkICNjY2M7IH0gdGQgeyBwYWRkaW5nOiAxMHB4OyB9YH0KICA8L3N0eWxlPgogIDx0YWJsZT4KICAgIHt0aGlzLnN0YXRlLmFzc2V0cy5tYXAoKGFzc2V0LCBpbmRleCkgPT4gKAogICAgICA8dHI%2BCiAgICAgICAge2Fzc2V0Lm1hcCgoZGF0YSkgPT4gKDx0ZD57ZGF0YX08L3RkPikpfQogICAgICAgIDx0ZD4KICAgICAgICAgIHtpbmRleCA%2BIDAgJiYgPGJ1dHRvbiBvbmNsaWNrPXsoKSA9PiB0aGlzLnJlbW92ZShpbmRleCl9PnJlbW92ZTwvYnV0dG9uPn0KICAgICAgICA8L3RkPgogICAgICA8L3RyPgogICAgKSl9CiAgPC90YWJsZT4KICAKICA8YnV0dG9uIG9uY2xpY2s9eygpID0%2BIHRoaXMuYWRkKCl9PkFkZCBhc3NldDwvYnV0dG9uPgo8L3RlbXBsYXRlPg%3D%3D

I also should mention that user facing API will change  drastically in near future when v1.0 will be released. Preview can be viewed on https://github.com/radi-js/radi/tree/huskey branch (docs are still being written).

**Comment by ryansolid** [comment]
That update appears to be non-keyed as in DOM nodes are re-purposed. So if you have a list of 5 items, and delete the first, it is actually the last DOM node that is deleted and all the content shifts up. Does radi.js support keyed updates as well?
